/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andre' at '11/08/16 16:30' with Gradle 2.12
 *
 * @author andre, @date 11/08/16 16:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
