/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andre.alcantara' at '4/13/16 8:59 AM' with Gradle 2.12
 *
 * @author andre.alcantara, @date 4/13/16 8:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
