/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andre' at '16/06/16 18:38' with Gradle 2.12
 *
 * @author andre, @date 16/06/16 18:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
