import org.junit.Test;
import br.com.ifquestao.HomeBean;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'andre' at '11/1/16 4:14 PM' with Gradle 3.1
 *
 * @author andre, @date 11/1/16 4:14 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        HomeBean classUnderTest = new HomeBean();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.stringParaPassarNoTest());    }
}
